### ISSUE TITLE
'overlays' folders is added to .gitignore

### ISSUE THREAD

**Issue by tmttn** [binduwavell/generator-alfresco#102]
When importing the code generated by `yo alfresco` into IntelliJ, and after enabling Maven support, IntelliJ creates an 'overlays' folder under project_name/repo/..., containing thousands of files.

This folder should not be checked in on source control, and therefore it would be nice to include it to .gitignore.

**Comment by binduwavell** [comment]
Thanks for reaching out the other day and for adding this issue @tmetten!
