### ISSUE TITLE
validation error when providing negotiation values in webscript generator

### ISSUE THREAD

**Issue by sammyangels** [binduwavell/generator-alfresco#116]
When running yo alfresco:webscript to generate scaffolding for a webscript, I was unable to complete the process, because I kept getting an 'Invalid format' error during the negotiation values option (format=mimetype).

I tried 'json=application/json' and received the error. I subsequently tested 'html=text/html' and 'xml=text/xml', and then copied the suggested input from the error message itself, but kept receiving the same error.

The error doesn't occur when running the command in one line (using the '-n json=application/json' option).

I'd be willing to take a look at it, but since I'm rather inexperienced, this might take a while :)

**Comment by binduwavell** [comment]
Sammy, thanks so much for reporting this issue. Can you tell me what version of node, what version of yo and when you pulled generator-alfresco?

**Comment by sammyangels** [comment]
Node version 3.9.0, Yo version 1.8.4.

I pulled generator-alfresco a while ago, but I'm pretty sure I updated it today.

**Comment by binduwavell** [comment]
Code is not tested with node 3 (I was under the impression that no one used that :) ). We test with 0.10, 0.12, 4, 5 and 6. So probably not that. 

I have not tried with yo 1.8.4, last version I tested with was 1.8.3, I'll re run the tests.

Please run `npm install -g binduwavell/generator-alfresco` Or update your clone if you are using a local copy. If you are using a local copy please re run `npm link`.

I'll get back with test results shortly.

**Comment by sammyangels** [comment]
Oops, my bad, node version seems to be 5.6.0

**Comment by binduwavell** [comment]
I just created a new project with `yo alfresco` and then created a pair of amps with `yo alfresco:amp`. Finally I ran `yo alfresco:webscript` and it worked without issue.

Could you provide me with the .yo-rc.json file from the root of your project and the values you are providing to each prompt to `yo alfresco:webscript`. Sorry there are a lot of them, but it's possible there is some dependent value issue going on.

Thanks Sammy!

**Comment by sammyangels** [comment]
I've attached a copy of the .yo-rc.json file of the project, and some screenshots of the values I was providing at each prompt. However, I just cloned a local copy and ran npm link, and now it works fine. Maybe I didn't actually update the generator like I thought I did... 😞 

[yo-rc.json_COPY.zip](https://github.com/binduwavell/generator-alfresco/files/304979/yo-rc.json_COPY.zip)
![screen shot 2016-06-08 at 16 31 55](https://cloud.githubusercontent.com/assets/1886071/15898104/38a2639c-2d97-11e6-9e8e-1158cc1eeb87.png)
![screen shot 2016-06-08 at 16 32 12](https://cloud.githubusercontent.com/assets/1886071/15898108/3aeb8d86-2d97-11e6-8f73-ea30158bea30.png)

**Comment by binduwavell** [comment]
Awesome, are you OK with me closing this ticket then?

**Comment by sammyangels** [comment]
Yes! 😄

**Comment by binduwavell** [comment]
Much appreciated Sammy.
