### ISSUE TITLE
add local amp is not working under window

### ISSUE THREAD

**Issue by yregaieg** [binduwavell/generator-alfresco#122]
It looks like the add local amp sub-generator is not working on Windows. So far, I tried the following:
- Running in interactive mode: after executing `yo alfresco:amp`, I select local, then select the amp I want to add to my project from the amp|amp_share folders then enter project properties (groupId, artefactId, ...). In this case, the sub-generator quits silently without any warning nor message.
- Pre-entering properties in the command: after executing `yo alfresco:amp -A local -p amps\myAmp.amp -g my.group.id -a my-artefact-id -v 1.1`, and in this case I get prompted for which amp I want to install (although I already included that info in command parameters) and after I select the desired amp, I get a list with all the other parameters I specified when invoking the command and the sub-generators quit silently without any warning/notification.

I did a little digging, and from where I stand, it looks like the issue is due to the difference between folder delimiters in windows|linux. As you can see [here](https://github.com/binduwavell/generator-alfresco/blob/master/generators/amp-add-local/index.js#L95) the sub-generator is testing on the presence of "amps/" which is different from "amps\" on windows systems.

**Comment by binduwavell** [comment]
Thanks much for this very informative report. May take a couple days to dig into this, hope that's OK. Let me know if urgent and we can probably work something out :)
