### ISSUE TITLE
Changes to alfresco-global.properties in module are not picked up

### ISSUE THREAD

**Issue by vprince1** [binduwavell/generator-alfresco#129]
When I change the "version" property of a module from the default "1.0.0-SNAPSHOT" to something custom like "ZIA-0.1.2", the alfresco-global.properties changes are not picked up.

`"generatorVersion": "0.9.0",
"sdkVersion": "2.2.0",
"archetypeVersion": "2.2.0",
"projectVersion": "1.0.0-SNAPSHOT",
"communityOrEnterprise": "Enterprise",`

Steps to reproduce:
1) Add new amp module
2) make changes to alfreco-global.properties in your module and verify they are picked up
3) Now change the "version" in customization/"your amp project"/pom.xml
4) Make a change to 'alfresco-global.properties' and start the server
5) You will notice that the new property is not picked up.. You can look in runner/ and you will see the change is not present.

**Comment by vprince1** [comment]
I think if I run `yo alfresco` again and change the version from '1.0.0-SNAPSHOT' to 'ZIA-0.1.2' it might update all the right files. I need to test this.

**Comment by binduwavell** [comment]
@vprince1 , I'm not sure I completely understand. If you are saying alfresco-global.properties changes are not going live. Could you try a `mvn clean` after editing the file and before using one of the run scripts?

**Comment by binduwavell** [comment]
@vprince1, could you provide more details?

**Comment by binduwavell** [comment]
@vprince1 could you update this ticket?

**Comment by binduwavell** [comment]
@vprince1 could you provide more details or close if you aren't able to reproduce?
