### ISSUE TITLE
Fails on openJDK

### ISSUE THREAD

**Issue by vprince1** [binduwavell/generator-alfresco#130]
When I run `yo alfresco`, I got a java an error "We are unable to find a java executable. A compatible version of java is required.". I was forced to use Oracle java

**Comment by binduwavell** [comment]
@vprince1 I assume this is with the code that tries to check the Java version my parsing the response from `java -version`. Should be easy to generalize the regex used or simply add a new condition.

**Comment by binduwavell** [comment]
Apparently a bad assumption on my part, here is the version output from an openJDK instance:

``` shell
➜  bin ./java -version
java version "1.7.0_111"
OpenJDK Runtime Environment (IcedTea 2.6.7) (7u111-2.6.7-0ubuntu0.14.04.3)
OpenJDK 64-Bit Server VM (build 24.111-b01, mixed mode)
```

Here is how we are processing the output:

``` java
var match = this.getRegExpMatchFromProcessOutput(cmd, args, /^java version "([^"]*)"$/);
```

Looks like that should work just fine... So I guess I'll try to reproduce the issue somewhere that has openJDK.

**Comment by binduwavell** [comment]
Well, it seems that some versions of openJDK do report weird versions:

``` shell
root@8483efc5e39a:~/yoalf# java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
```

**Comment by binduwavell** [comment]
Found a non-prerelease version of OpenJDK returning: 

``` shell
openjdk version "1.8.0_91"
```

Updated code to try harder to find java binary if JAVA_HOME is not specified. Also updated parsing code to handle this version response format.
