### ISSUE TITLE
Broken assets when switching from Windows to Linux

### ISSUE THREAD

**Issue by yregaieg** [binduwavell/generator-alfresco#152]
For some reason, when the developer is using the generator from windows, and adding multiple sources amps to the project, windows path seperator is used `\` instead of `/` in `project-aio/runner/tomcat/context-*.xml` resulting in broken assets when accessing the application from the browser.

switching folder seperator to `/` seems to fix the issue.

**Comment by binduwavell** [comment]
Thanks @yregaieg will take a look at the code and get this fixed. Fingers crossed SDK 3 will be out soon and these tomcat files will be a distant memory :)

**Comment by yregaieg** [comment]
Not necessarily true, unless the generator provides an automated way to
migrate old projects 'yo alfresco: upgrade-sdk' for instance
