### ISSUE TITLE
explode-alf-sources.sh references non-existing projects

### ISSUE THREAD

**Issue by jrosler** [binduwavell/generator-alfresco#3]
If I rename/move the default repo-amp and share-amp, explode doesn't work as it assumes they exist. It might be better to explode based on amps_sources_templates/repo-amp and amps/source_templates/share-amp and then store the exploded files somewhere else as the templates should always be there.

**Comment by jrosler** [comment]
Also, after this is fixed need to test the other *exploded.sh scripts against new locations.

**Comment by binduwavell** [comment]
I agree with the suggestion to explode the amps_sources_templates. I don't understand the comment about moving where the exploded stuff lives?

**Comment by jrosler** [comment]
Never mind. When I looked at it, i didn't see the output dir as ../exploded. I was thinking it was getting dumped into the amp folders. The change would probably be to dump it to ../../exploded if you ran it from amps_sources_templates/*amp.

**Comment by binduwavell** [comment]
It would be cool if we could use the saved modules under `source_templates` to pull in the required sources...

**Comment by binduwavell** [comment]
Vijay addressed this (see above)
