### ISSUE TITLE
get conflictor to silently overwrite certain system files

### ISSUE THREAD

**Issue by vprince1** [binduwavell/generator-alfresco#30]
When the user runs a sub-generator or re-runs the generator to update certain values, we should not prompt the user to confirm overwrite of certain files like pom.xml.

**Comment by binduwavell** [comment]
Note this was originally discussed in PR #26. I was not able to find a reasonable way of doing this, but did add a notice to the user in the amp generator where @jrosler referenced the problem... So this is really an opportunity for us to do a deeper dive (see references in PR #26 for starting points.)
