### ISSUE TITLE
share-amp and repo-amp should be moved under customizations folder (previously amps_source)

### ISSUE THREAD

**Issue by jrosler** [binduwavell/generator-alfresco#4]
Seems like share-amp and repo-amp should be moved to amps_source as part of initial generator since that's where the docs say custom amps should go per amps_source/README.md.

**Comment by binduwavell** [comment]
In principle, I agree, in practice, I think we should ask folks as part of the initial interview. Will leave this here as a reminder once we have the module registry completed.

**Comment by binduwavell** [comment]
Quick update on this, code in the feature-amp branch is now able to substantially do this. There are a couple of items that still need doing. We need to update the tomcat context files in the runner module and we need to figure out what we are doing about the share page object testing stuff in the generated share amps.

**Comment by binduwavell** [comment]
Technically this can be done now, if you run `yo alfresco` and indicate the sample amps should be removed and then run `yo alfresco:amp` it will create the new modules in the right place. I'm not sure if we should do this automatically in `yo alfresco` or ask folks in there if they want to do this right from the start or leave it as it is now, what do you think? (@jrosler @vprince1 @michaeljmuller)

**Comment by binduwavell** [comment]
I changed the default behavior to not create source amps. If the user accepts this value then the main generator will suggest that the users use `yo alfresco:amp` to add some source amps.
