### ISSUE TITLE
action sub-generator should include resource bundle with title and description

### ISSUE THREAD

**Issue by jrosler** [binduwavell/generator-alfresco#71]
The action sub generator should add a resource bundle bean to the action context file (replace bean id based on action name - below it is foo). This is used within the by share when displaying the action name in folder rules.

```
  <bean id="foo-action-properties" class="org.alfresco.i18n.ResourceBundleBootstrapComponent">
    <property name="resourceBundles">
      <list>
        <value>alfresco/module/${project.artifactId}/messages/custom-action-config</value>
      </list>
    </property>
  </bean>
```

This points to a custom-action-config.properties file (in this case under messages folder that would need to be created)

Within the properties file, list the title and description based on the bean id of the action. In the case below the bean id is demo.foo.

```
demo.foo.title=File SafetyPass Documents
demo.foo.description=Filing action used to file SafetyPass documents when imported by Ephesoft
```

**Comment by binduwavell** [comment]
I was literally just looking at the following information: https://wiki.alfresco.com/wiki/Custom_Actions which outlines how to set this up :)

**Comment by jrosler** [comment]
:-)
Just thought I'd add this since we spoke about it today.

**Comment by binduwavell** [comment]
I should have said in my previous comment, thank you very much for writing this up, it is much appreciated!
