### ISSUE TITLE
project files created in wrong directory

### ISSUE THREAD

**Issue by michaeljmuller** [binduwavell/generator-alfresco#8]
I ran "yo alfresco" and it created all the files/directories in the current working directory.  So I cleaned them all up, created a project directory, cd'd into the project directory and re-ran "yo alfresco", but it put the project files up a level in the same place as the first time I ran the generator.

**Comment by vprince1** [comment]
In the top level folder, you will see a file ".yo-rc.json”. just rename it to “.yo-rc.json-bk” and retry. Deleting that file might also work.

Vijay

**Comment by michaeljmuller** [comment]
Yes, deleting the file is a effective workaround.

**Comment by binduwavell** [comment]
That is just how yeoman works. How do you think we could best warn people of this?

We could see if the .yo-rc file exists and none of the other project files and display a warning or bail?

**Comment by michaeljmuller** [comment]
Brainstorming:
- Modify generator to create project directory 
- Modify README to indicate that you should manually create project dir and then cd into it before typing "yo alfresco"

**Comment by binduwavell** [comment]
I don't think we should change the default behavior of working in the "current" directory. The README does indicate a project directory should be created and the `yo alfresco` command should be run there. Per your suggestion in my office we should update the example to include the mkdir and cd commands.

**Comment by binduwavell** [comment]
After reviewing the code in the yeoman team provided generator-generator. It seems that there is a good case for creating the project folder if the artifactId does not match the current working directory name. Vijay will likely take this on as his next challenge.

**Comment by vprince1** [comment]
I am planning to make the following changes
Scenario 1: The folder where the user runs 'yo alfresco' does not have any .yo-rc.json file in its parent hierarchy
1) When the user runs 'yo alfresco', the default artifactId will be the folder name where the command is run
2) If the user changes the artifactId, we will create a sub-directory with the same name as that of the artifactId and run the generator

Scenario 2: The folder where the user runs 'yo alfresco' either has a .yo-rc.json or its parents have the file
1) When the user runs 'yo alfresco', we will show a message saying "WARN: You are running the command within an existing project <%= artifactId => located at <%= projectPath =>"
2) If the user proceeds and changes the artifactId, we will not create any folder but will show a message saying, "Updating the artifactId can lead to unexpected issue. Proceed with caution"

Let me know your thoughts.

**Comment by binduwavell** [comment]
Awesome @vprince1, once you complete the listed tasks, you will have also have resolved #16.
