### ISSUE TITLE
README says to use "yo alfresco:amp", but no such generator is installed

### ISSUE THREAD

**Issue by michaeljmuller** [binduwavell/generator-alfresco#9]
My project was generated with repo-amp and share-amp moved into amps_source_templates.  I tried to create an amp for my project's custom code using the "yo alfresco:amp" command (as indicated by the README), but I get an error that says no such generator is installed.

**Comment by vprince1** [comment]
I think that generator is in the feature-amp branch. It is not yet merged with master.

Don’t you see a repo-amp and share-amp in the root directory?

Vijay

**Comment by michaeljmuller** [comment]
No, those are in the amps_source_templates directory.

**Comment by binduwavell** [comment]
amps_source_templates is a backup of the archetype generated amps that will be used as the source material when yo alfresco:amp is stamping out new source amp modules. Our project source amps should go under amps_source.

Not sure which version of the generator you are using if the README references `yo alfresco:amp`. As Vijay mentions, there is a branch where I'm working on that sub-generator but it is VERY rough and it does not fix up the tomcat context files in the runner module yet.

**Comment by michaeljmuller** [comment]
I'm using the version of the generator that was provided when I executed:

npm install -g binduwavell/generator-alfresco

as indicated in the project's README.  I assume it's the most recent code from the "main" branch.

Sounds like the READMEs are just out-of-sync with the code base.

**Comment by binduwavell** [comment]
We just discussed, this comment is in the generated project amps_share/README maybe other places.

**Comment by binduwavell** [comment]
I updated the README files to say that yo alfresco:amp was not available yet, and now it is available and I forgot to update the README files to indicate it is possible. So now all we have to do is remove some text from the README files.

**Comment by binduwavell** [comment]
Final update in #19
