### ISSUE TITLE
must not use --version as an option in sub/generators

### ISSUE THREAD

**Issue by binduwavell** [binduwavell/generator-alfresco#97]
It appears that yo takes over --version and we don't receive associated input. 

I guess we should prefer --model-version, --artifact-version, etc (as opposed to --ver)... what do you think?

Consider updating model sub-generator to use the requiredVersionFilter from the common fitlers (and probably add USAGE info to explain that weirdness.)

**Comment by vprince1** [comment]
If we run 'yo alfresco:amp --version' we just get the version of yo. I am assuming this is the issue we are trying to solve.

It looks like we only need to update the options for 'amp-add-local' and 'amp-add-remote'. The other sub-generators do not use '--version'. 'yo alfresco:model --model-version=1.2' works as expected.

The 'model-version' already uses 'modelFilters.versionNumberFilter' that handles the number correctly. I am assuming you want to use the 'requiredVersionFilter' to keep it common between other sub-generators.

**Comment by binduwavell** [comment]
Vijay, per our discussion the other day, I think you have outlined exactly what I had in mind when I wrote up this issue. Sorry it wasn't more clear to begin with.
